# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG
spring.datasource.url=jdbc:sqlserver://DESKTOP-L4SNF0H;databaseName=poc_karaoke;integratedSecurity=true;encrypt=false;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver